export interface ITournamentDto {
    id: string,
    name: string,
    code: string,
    description: string,
    banner: string,
    public: boolean,
    playersPublic: boolean,
    done: boolean,
    minTeamSize: number,
    maxTeamSixe: number,
    minRank: number,
    maxRank: number,
    protects: boolean,
    warmups: boolean,
    regOpen: boolean,
    applicationOpen: boolean,
    regDeadline: Date,
    applicationDeadline: Date,
    discordLink: string,
    forumLink: string,
    challongeLink: string,
    countries: string[]
}