INSERT INTO status (name) VALUES ('pending');
INSERT INTO status (name) VALUES ('accepted');
INSERT INTO status (name) VALUES ('rejected');
INSERT INTO status (name) VALUES ('retracted');
INSERT INTO status (name) VALUES ('registered');
INSERT INTO status (name) VALUES ('active');
INSERT INTO status (name) VALUES ('eliminated');
INSERT INTO status (name) VALUES ('disqualified');

INSERT INTO stage_type (name) VALUES ('standard');
INSERT INTO stage_type (name) VALUES ('qualifier');

INSERT INTO map_type (name) VALUES ('RC');
INSERT INTO map_type (name) VALUES ('LN');
INSERT INTO map_type (name) VALUES ('HB');
INSERT INTO map_type (name) VALUES ('SV');
INSERT INTO map_type (name) VALUES ('TB');

INSERT INTO role (name) VALUES ('player');
INSERT INTO role (name) VALUES ('host');
INSERT INTO role (name) VALUES ('admin');
INSERT INTO role (name) VALUES ('mappooler');
INSERT INTO role (name) VALUES ('mapper');
INSERT INTO role (name) VALUES ('playtester');
INSERT INTO role (name) VALUES ('referee');
INSERT INTO role (name) VALUES ('streamer');
INSERT INTO role (name) VALUES ('commentator');
INSERT INTO role (name) VALUES ('sheeter');
INSERT INTO role (name) VALUES ('gfx');

INSERT INTO country (name, iso2) VALUES ('Andorra', 'AD');
INSERT INTO country (name, iso2) VALUES ('United Arab Emirates', 'AE');
INSERT INTO country (name, iso2) VALUES ('Afghanistan', 'AF');
INSERT INTO country (name, iso2) VALUES ('Antigua and Barbuda', 'AG');
INSERT INTO country (name, iso2) VALUES ('Anguilla', 'AI');
INSERT INTO country (name, iso2) VALUES ('Albania', 'AL');
INSERT INTO country (name, iso2) VALUES ('Armenia', 'AM');
INSERT INTO country (name, iso2) VALUES ('Angola', 'AO');
INSERT INTO country (name, iso2) VALUES ('Argentina', 'AR');
INSERT INTO country (name, iso2) VALUES ('American Samoa', 'AS');
INSERT INTO country (name, iso2) VALUES ('Austria', 'AT');
INSERT INTO country (name, iso2) VALUES ('Australia', 'AU');
INSERT INTO country (name, iso2) VALUES ('Aruba', 'AW');
INSERT INTO country (name, iso2) VALUES ('Allard Islands', 'AX');
INSERT INTO country (name, iso2) VALUES ('Azerbaijan', 'AZ');
INSERT INTO country (name, iso2) VALUES ('Bosnia and Herzegovina', 'BA');
INSERT INTO country (name, iso2) VALUES ('Barbados', 'BB');
INSERT INTO country (name, iso2) VALUES ('Bangladesh', 'BD');
INSERT INTO country (name, iso2) VALUES ('Belgium', 'BE');
INSERT INTO country (name, iso2) VALUES ('Burkina Faso', 'BF');
INSERT INTO country (name, iso2) VALUES ('Bulgaria', 'BG');
INSERT INTO country (name, iso2) VALUES ('Bahrain', 'BH');
INSERT INTO country (name, iso2) VALUES ('Burundi', 'BI');
INSERT INTO country (name, iso2) VALUES ('Benin', 'BJ');
INSERT INTO country (name, iso2) VALUES ('Saint Barthelemy', 'BL');
INSERT INTO country (name, iso2) VALUES ('Bermuda', 'BM');
INSERT INTO country (name, iso2) VALUES ('Brunei Darussalam', 'BN');
INSERT INTO country (name, iso2) VALUES ('Bolivia', 'BO');
INSERT INTO country (name, iso2) VALUES ('Brazil', 'BR');
INSERT INTO country (name, iso2) VALUES ('Bahamas', 'BS');
INSERT INTO country (name, iso2) VALUES ('Bhutan', 'BT');
INSERT INTO country (name, iso2) VALUES ('Botswana', 'BW');
INSERT INTO country (name, iso2) VALUES ('Belarus', 'BY');
INSERT INTO country (name, iso2) VALUES ('Belize', 'BZ');
INSERT INTO country (name, iso2) VALUES ('Canada', 'CA');
INSERT INTO country (name, iso2) VALUES ('Democratic Republic of the Congo', 'CD');
INSERT INTO country (name, iso2) VALUES ('Central African Republic', 'CF');
INSERT INTO country (name, iso2) VALUES ('Republic of the Congo', 'CG');
INSERT INTO country (name, iso2) VALUES ('Switzerland', 'CH');
INSERT INTO country (name, iso2) VALUES ('Cote d''Ivoire', 'CI');
INSERT INTO country (name, iso2) VALUES ('Chile', 'CL');
INSERT INTO country (name, iso2) VALUES ('Cameroon', 'CM');
INSERT INTO country (name, iso2) VALUES ('China', 'CN');
INSERT INTO country (name, iso2) VALUES ('Colombia', 'CO');
INSERT INTO country (name, iso2) VALUES ('Costa Rica', 'CR');
INSERT INTO country (name, iso2) VALUES ('Cuba', 'CU');
INSERT INTO country (name, iso2) VALUES ('Cape Verde', 'CV');
INSERT INTO country (name, iso2) VALUES ('Christmas Island', 'CX');
INSERT INTO country (name, iso2) VALUES ('Cyprus', 'CY');
INSERT INTO country (name, iso2) VALUES ('Czech Republic', 'CZ');
INSERT INTO country (name, iso2) VALUES ('Germany', 'DE');
INSERT INTO country (name, iso2) VALUES ('Djibouti', 'DJ');
INSERT INTO country (name, iso2) VALUES ('Denmark', 'DK');
INSERT INTO country (name, iso2) VALUES ('Dominica', 'DM');
INSERT INTO country (name, iso2) VALUES ('Dominican Republic', 'DO');
INSERT INTO country (name, iso2) VALUES ('Algeria', 'DZ');
INSERT INTO country (name, iso2) VALUES ('Ecuador', 'EC');
INSERT INTO country (name, iso2) VALUES ('Estonia', 'EE');
INSERT INTO country (name, iso2) VALUES ('Egypt', 'EG');
INSERT INTO country (name, iso2) VALUES ('Eritrea', 'ER');
INSERT INTO country (name, iso2) VALUES ('Spain', 'ES');
INSERT INTO country (name, iso2) VALUES ('Ethiopia', 'ET');
INSERT INTO country (name, iso2) VALUES ('Finland', 'FI');
INSERT INTO country (name, iso2) VALUES ('Fiji', 'FJ');
INSERT INTO country (name, iso2) VALUES ('Falkland Islands (Malvinas)', 'FK');
INSERT INTO country (name, iso2) VALUES ('Micronesia', 'FM');
INSERT INTO country (name, iso2) VALUES ('Faroe Islands', 'FO');
INSERT INTO country (name, iso2) VALUES ('France', 'FR');
INSERT INTO country (name, iso2) VALUES ('Gabon', 'GA');
INSERT INTO country (name, iso2) VALUES ('United Kingdom', 'GB');
INSERT INTO country (name, iso2) VALUES ('Grenada', 'GD');
INSERT INTO country (name, iso2) VALUES ('Georgia', 'GE');
INSERT INTO country (name, iso2) VALUES ('French Guiana', 'GF');
INSERT INTO country (name, iso2) VALUES ('Guernsey', 'GG');
INSERT INTO country (name, iso2) VALUES ('Ghana', 'GH');
INSERT INTO country (name, iso2) VALUES ('Gibraltar', 'GI');
INSERT INTO country (name, iso2) VALUES ('Greenland', 'GL');
INSERT INTO country (name, iso2) VALUES ('Gambia', 'GM');
INSERT INTO country (name, iso2) VALUES ('Guinea', 'GN');
INSERT INTO country (name, iso2) VALUES ('Guadeloupe', 'GP');
INSERT INTO country (name, iso2) VALUES ('Equatorial Guinea', 'GQ');
INSERT INTO country (name, iso2) VALUES ('Greece', 'GR');
INSERT INTO country (name, iso2) VALUES ('Guatemala', 'GT');
INSERT INTO country (name, iso2) VALUES ('Guam', 'GU');
INSERT INTO country (name, iso2) VALUES ('Guinea-Bissau', 'GW');
INSERT INTO country (name, iso2) VALUES ('Guyana', 'GY');
INSERT INTO country (name, iso2) VALUES ('Hong Kong', 'HK');
INSERT INTO country (name, iso2) VALUES ('Heard Island and McDonald Islands', 'HM');
INSERT INTO country (name, iso2) VALUES ('Honduras', 'HN');
INSERT INTO country (name, iso2) VALUES ('Croatia', 'HR');
INSERT INTO country (name, iso2) VALUES ('Haiti', 'HT');
INSERT INTO country (name, iso2) VALUES ('Hungary', 'HU');
INSERT INTO country (name, iso2) VALUES ('Indonesia', 'ID');
INSERT INTO country (name, iso2) VALUES ('Ireland', 'IE');
INSERT INTO country (name, iso2) VALUES ('Israel', 'IL');
INSERT INTO country (name, iso2) VALUES ('Isle of Man', 'IM');
INSERT INTO country (name, iso2) VALUES ('India', 'IN');
INSERT INTO country (name, iso2) VALUES ('Iraq', 'IQ');
INSERT INTO country (name, iso2) VALUES ('Iran', 'IR');
INSERT INTO country (name, iso2) VALUES ('Iceland', 'IS');
INSERT INTO country (name, iso2) VALUES ('Italy', 'IT');
INSERT INTO country (name, iso2) VALUES ('Jersey', 'JE');
INSERT INTO country (name, iso2) VALUES ('Jamaica', 'JM');
INSERT INTO country (name, iso2) VALUES ('Jordan', 'JO');
INSERT INTO country (name, iso2) VALUES ('Japan', 'JP');
INSERT INTO country (name, iso2) VALUES ('Kenya', 'KE');
INSERT INTO country (name, iso2) VALUES ('Kyrgyzstan', 'KG');
INSERT INTO country (name, iso2) VALUES ('Cambodia', 'KH');
INSERT INTO country (name, iso2) VALUES ('Kiribati', 'KI');
INSERT INTO country (name, iso2) VALUES ('Comoros', 'KM');
INSERT INTO country (name, iso2) VALUES ('Saint Kitts and Nevis', 'KN');
INSERT INTO country (name, iso2) VALUES ('South Korea', 'KR');
INSERT INTO country (name, iso2) VALUES ('Kuwait', 'KW');
INSERT INTO country (name, iso2) VALUES ('Cayman Islands', 'KY');
INSERT INTO country (name, iso2) VALUES ('Kazakhstan', 'KZ');
INSERT INTO country (name, iso2) VALUES ('Lao', 'LA');
INSERT INTO country (name, iso2) VALUES ('Lebanon', 'LB');
INSERT INTO country (name, iso2) VALUES ('Saint Lucia', 'LC');
INSERT INTO country (name, iso2) VALUES ('Liechtenstein', 'LI');
INSERT INTO country (name, iso2) VALUES ('Sri Lanka', 'LK');
INSERT INTO country (name, iso2) VALUES ('Liberia', 'LR');
INSERT INTO country (name, iso2) VALUES ('Lesotho', 'LS');
INSERT INTO country (name, iso2) VALUES ('Lithuania', 'LT');
INSERT INTO country (name, iso2) VALUES ('Luxembourg', 'LU');
INSERT INTO country (name, iso2) VALUES ('Latvia', 'LV');
INSERT INTO country (name, iso2) VALUES ('Libya', 'LY');
INSERT INTO country (name, iso2) VALUES ('Morocco', 'MA');
INSERT INTO country (name, iso2) VALUES ('Monaco', 'MC');
INSERT INTO country (name, iso2) VALUES ('Moldova', 'MD');
INSERT INTO country (name, iso2) VALUES ('Montenegro', 'ME');
INSERT INTO country (name, iso2) VALUES ('Saint Martin (French part)', 'MF');
INSERT INTO country (name, iso2) VALUES ('Madagascar', 'MG');
INSERT INTO country (name, iso2) VALUES ('Marshall Islands', 'MH');
INSERT INTO country (name, iso2) VALUES ('Macedonia', 'MK');
INSERT INTO country (name, iso2) VALUES ('Mali', 'ML');
INSERT INTO country (name, iso2) VALUES ('Myanmar', 'MM');
INSERT INTO country (name, iso2) VALUES ('Mongolia', 'MN');
INSERT INTO country (name, iso2) VALUES ('Macao', 'MO');
INSERT INTO country (name, iso2) VALUES ('Northern Mariana Islands', 'MP');
INSERT INTO country (name, iso2) VALUES ('Martinique', 'MQ');
INSERT INTO country (name, iso2) VALUES ('Mauritania', 'MR');
INSERT INTO country (name, iso2) VALUES ('Montserrat', 'MS');
INSERT INTO country (name, iso2) VALUES ('Malta', 'MT');
INSERT INTO country (name, iso2) VALUES ('Mauritius', 'MU');
INSERT INTO country (name, iso2) VALUES ('Maldives', 'MV');
INSERT INTO country (name, iso2) VALUES ('Malawi', 'MW');
INSERT INTO country (name, iso2) VALUES ('Mexico', 'MX');
INSERT INTO country (name, iso2) VALUES ('Malaysia', 'MY');
INSERT INTO country (name, iso2) VALUES ('Mozambique', 'MZ');
INSERT INTO country (name, iso2) VALUES ('Namibia', 'NA');
INSERT INTO country (name, iso2) VALUES ('New Caledonia', 'NC');
INSERT INTO country (name, iso2) VALUES ('Niger', 'NE');
INSERT INTO country (name, iso2) VALUES ('Norfolk Island', 'NF');
INSERT INTO country (name, iso2) VALUES ('Nigeria', 'NG');
INSERT INTO country (name, iso2) VALUES ('Nicaragua', 'NI');
INSERT INTO country (name, iso2) VALUES ('Netherlands', 'NL');
INSERT INTO country (name, iso2) VALUES ('Norway', 'NO');
INSERT INTO country (name, iso2) VALUES ('Nepal', 'NP');
INSERT INTO country (name, iso2) VALUES ('Nauru', 'NR');
INSERT INTO country (name, iso2) VALUES ('Niue', 'NU');
INSERT INTO country (name, iso2) VALUES ('New Zealand', 'NZ');
INSERT INTO country (name, iso2) VALUES ('Oman', 'OM');
INSERT INTO country (name, iso2) VALUES ('Panama', 'PA');
INSERT INTO country (name, iso2) VALUES ('Peru', 'PE');
INSERT INTO country (name, iso2) VALUES ('French Polynesia', 'PF');
INSERT INTO country (name, iso2) VALUES ('Papua New Guinea', 'PG');
INSERT INTO country (name, iso2) VALUES ('Philippines', 'PH');
INSERT INTO country (name, iso2) VALUES ('Pakistan', 'PK');
INSERT INTO country (name, iso2) VALUES ('Poland', 'PL');
INSERT INTO country (name, iso2) VALUES ('Saint Pierre and Miquelon', 'PM');
INSERT INTO country (name, iso2) VALUES ('Pitcairn', 'PN');
INSERT INTO country (name, iso2) VALUES ('Puerto Rico', 'PR');
INSERT INTO country (name, iso2) VALUES ('Palestine', 'PS');
INSERT INTO country (name, iso2) VALUES ('Portugal', 'PT');
INSERT INTO country (name, iso2) VALUES ('Palau', 'PW');
INSERT INTO country (name, iso2) VALUES ('Paraguay', 'PY');
INSERT INTO country (name, iso2) VALUES ('Qatar', 'QA');
INSERT INTO country (name, iso2) VALUES ('Reunion', 'RE');
INSERT INTO country (name, iso2) VALUES ('Romania', 'RO');
INSERT INTO country (name, iso2) VALUES ('Serbia', 'RS');
INSERT INTO country (name, iso2) VALUES ('Russian Federation', 'RU');
INSERT INTO country (name, iso2) VALUES ('Rwanda', 'RW');
INSERT INTO country (name, iso2) VALUES ('Saudi Arabia', 'SA');
INSERT INTO country (name, iso2) VALUES ('Solomon Islands', 'SB');
INSERT INTO country (name, iso2) VALUES ('Seychelles', 'SC');
INSERT INTO country (name, iso2) VALUES ('Sudan', 'SD');
INSERT INTO country (name, iso2) VALUES ('Sweden', 'SE');
INSERT INTO country (name, iso2) VALUES ('Singapore', 'SG');
INSERT INTO country (name, iso2) VALUES ('Saint Helena', 'SH');
INSERT INTO country (name, iso2) VALUES ('Slovenia', 'SI');
INSERT INTO country (name, iso2) VALUES ('Svalbard and Jan Mayen', 'SJ');
INSERT INTO country (name, iso2) VALUES ('Slovakia', 'SK');
INSERT INTO country (name, iso2) VALUES ('Sierra Leone', 'SL');
INSERT INTO country (name, iso2) VALUES ('San Marino', 'SM');
INSERT INTO country (name, iso2) VALUES ('Senegal', 'SN');
INSERT INTO country (name, iso2) VALUES ('Somalia', 'SO');
INSERT INTO country (name, iso2) VALUES ('Suriname', 'SR');
INSERT INTO country (name, iso2) VALUES ('South Sudan', 'SS');
INSERT INTO country (name, iso2) VALUES ('Sao Tome and Principe', 'ST');
INSERT INTO country (name, iso2) VALUES ('El Salvador', 'SV');
INSERT INTO country (name, iso2) VALUES ('Syrian Arab Republic', 'SY');
INSERT INTO country (name, iso2) VALUES ('Swaziland', 'SZ');
INSERT INTO country (name, iso2) VALUES ('Turks and Caicos Islands', 'TC');
INSERT INTO country (name, iso2) VALUES ('Chad', 'TD');
INSERT INTO country (name, iso2) VALUES ('Togo', 'TG');
INSERT INTO country (name, iso2) VALUES ('Thailand', 'TH');
INSERT INTO country (name, iso2) VALUES ('Tajikistan', 'TJ');
INSERT INTO country (name, iso2) VALUES ('Timor-Leste', 'TL');
INSERT INTO country (name, iso2) VALUES ('Turkmenistan', 'TM');
INSERT INTO country (name, iso2) VALUES ('Tunisia', 'TN');
INSERT INTO country (name, iso2) VALUES ('Tonga', 'TO');
INSERT INTO country (name, iso2) VALUES ('Turkey', 'TR');
INSERT INTO country (name, iso2) VALUES ('Trinidad and Tobago', 'TT');
INSERT INTO country (name, iso2) VALUES ('Tuvalu', 'TV');
INSERT INTO country (name, iso2) VALUES ('Taiwan', 'TW');
INSERT INTO country (name, iso2) VALUES ('United Republic of Tanzania', 'TZ');
INSERT INTO country (name, iso2) VALUES ('Ukraine', 'UA');
INSERT INTO country (name, iso2) VALUES ('Uganda', 'UG');
INSERT INTO country (name, iso2) VALUES ('United States', 'US');
INSERT INTO country (name, iso2) VALUES ('Uruguay', 'UY');
INSERT INTO country (name, iso2) VALUES ('Uzbekistan', 'UZ');
INSERT INTO country (name, iso2) VALUES ('Holy See (Vatican City State)', 'VA');
INSERT INTO country (name, iso2) VALUES ('Saint Vincent and the Grenadines', 'VC');
INSERT INTO country (name, iso2) VALUES ('Venezuela', 'VE');
INSERT INTO country (name, iso2) VALUES ('British Virgin Islands', 'VG');
INSERT INTO country (name, iso2) VALUES ('US Virgin Islands', 'VI');
INSERT INTO country (name, iso2) VALUES ('Vietnam', 'VN');
INSERT INTO country (name, iso2) VALUES ('Vanuatu', 'VU');
INSERT INTO country (name, iso2) VALUES ('Samoa', 'WS');
INSERT INTO country (name, iso2) VALUES ('Kosovo', 'XK');
INSERT INTO country (name, iso2) VALUES ('Yemen', 'YE');
INSERT INTO country (name, iso2) VALUES ('Mayotte', 'YT');
INSERT INTO country (name, iso2) VALUES ('South Africa', 'ZA');
INSERT INTO country (name, iso2) VALUES ('Zambia', 'ZM');
INSERT INTO country (name, iso2) VALUES ('Zimbabwe', 'ZW');